using System;
using OwlPack.Runtime;

namespace Kingmaker.Code.View.Bridge.Enums;

[OwlPackOldName("Kingmaker.Code.UI.MVVM.TooltipElement, Code")]
public enum TooltipElement
{
	Name,
	Description,
	ArtisticDescription,
	[Obsolete("Removed Enchantments")]
	EnchantmentsDescription,
	Count,
	ItemType,
	Subname,
	Price,
	SellPrice,
	Weight,
	Wielder,
	WielderSlot,
	EquippedSlot,
	ProficiencyGroup,
	Size,
	Twohanded,
	AttackType,
	Attack,
	Damage,
	Penetration,
	PhysicalDamage,
	Piercing,
	Bludgeoning,
	Slashing,
	RateOfFire,
	CriticalChance,
	Defense,
	[Obsolete]
	Range,
	EquipDamage,
	Enhancement,
	ArmorClass,
	MaxDexterity,
	[Obsolete]
	ArmorCheckPenalty,
	[Obsolete]
	ArcaneSpellFailure,
	Charges,
	[Obsolete]
	CasterLevel,
	DifficultyClass,
	ShortDescription,
	LongDescription,
	Force,
	Fire,
	Cold,
	Sonic,
	Electricity,
	Acid,
	NegativeEnergy,
	PositiveEnergy,
	Holy,
	Unholy,
	Divine,
	Qualities,
	Duration,
	Target,
	SavingThrow,
	FullArmorClass,
	[Obsolete]
	CastingTime,
	[Obsolete]
	SpellDescriptor,
	MaxDistance,
	MinStrength,
	ReloadAP,
	ArmorDeflection,
	DamageReduction,
	[Obsolete("Defence")]
	ArmorDodgePenalty,
	[Obsolete("HitChance")]
	SingleAdditionalHitChance,
	[Obsolete("HitChance")]
	BurstAdditionalHitChance,
	AoeAdditionalHitChance,
	WeaponFamily,
	WeaponCategory,
	ItemCost,
	Cooldown,
	[Obsolete("Defence")]
	DodgeReduction,
	ArmorDamageReduceDescription,
	ArmourDodgeChanceDescription,
	BaseDamage,
	Replenishing,
	RateOfFireMelee,
	Durability,
	OverpenetrationChance,
	Recoil,
	HitChance
}
