using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;

[assembly: IgnoresAccessChecksTo("Code")]
[assembly: IgnoresAccessChecksTo("LocalizationShared")]
[assembly: IgnoresAccessChecksTo("Owlcat.BehaviourTrees.Runtime")]
[assembly: IgnoresAccessChecksTo("Owlcat.Core.Attributes")]
[assembly: IgnoresAccessChecksTo("Owlcat.Editor.Visual.UserData")]
[assembly: IgnoresAccessChecksTo("Owlcat.Logging.Runtime")]
[assembly: IgnoresAccessChecksTo("Owlcat.Runtime.Core")]
[assembly: IgnoresAccessChecksTo("Owlcat.Runtime.Validation")]
[assembly: IgnoresAccessChecksTo("Owlcat.Runtime.Visual")]
[assembly: IgnoresAccessChecksTo("Owlcat.ShaderLibrary.Visual")]
[assembly: IgnoresAccessChecksTo("Owlcat.Shaders.Visual")]
[assembly: IgnoresAccessChecksTo("Owlcat.TaskScheduling")]
[assembly: IgnoresAccessChecksTo("Owlcat.UI.Controls")]
[assembly: IgnoresAccessChecksTo("Owlcat.UI.DH")]
[assembly: IgnoresAccessChecksTo("Owlcat.UI")]
[assembly: IgnoresAccessChecksTo("Owlcat.Visual.VertexPaint.PolybrushUtils")]
[assembly: IgnoresAccessChecksTo("RogueTrader.Code.ShaderConsts")]
[assembly: IgnoresAccessChecksTo("RogueTrader.QA.QAModeExceptionEvents")]
[assembly: IgnoresAccessChecksTo("RogueTrader.SharedTypes")]
[assembly: AssemblyCompany("UnityModManager")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyDescription("UnityModManager")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("UnityModManager")]
[assembly: AssemblyTitle("UnityModManager")]
[assembly: AssemblyVersion("1.0.0.0")]
[module: RefSafetyRules(11)]
